### ISSUE TITLE
/api/catalog/search/products don't return labels when using virtual catalogs

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-catalog#566] opened 2021-10-28 03:03 UTC
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Microsoft Edge Versão 95.0.1020.30
- Platform version: 3.87.0
- Module version: 3.73.0

### Expected behavior
Return respective label by region in aggregations labels field

### Actual behavior
return empty value in field labels

### Steps to reproduce
1. using a store with two languages or more
2. create a new virtual catalog
3. create a fisical category in virtual catalog
4. create a new virtual product, the product in original catalog have some "Product properties" a dictionary, multivalue and multi language
5. Search products using API shearch/products
6. the agregation field not return labels

virtual catalog
![image](https://user-images.githubusercontent.com/20837564/139178282-37c598c0-2fa4-492f-a1ac-4110825aab88.png)

properties in original product
![image](https://user-images.githubusercontent.com/20837564/139178049-541cad21-8a35-4b32-a10d-ca5d7eb0929b.png)

return of api/catalog/search/products not return labels in agregations 
![image](https://user-images.githubusercontent.com/20837564/139178131-c604cdfc-7509-4b70-82dc-ef806577984e.png)

**Comment by JoseCaetanoNeto** [comment] 2021-10-29 18:03
I'm setting up a test environment to release for you.

**Comment by JoseCaetanoNeto** [comment] 2021-11-01 11:05
Published test environment.
https://scrubup-dev.azurewebsites.net/
user virtosupport
pass Virtosupport

**Comment by JoseCaetanoNeto** [comment] 2021-11-03 12:09
i identified the steps to reproduce. You need to create properties linked to a category. If the property is created directly in the catalog, the problem does not manifest itself.

**Comment by dvvkgd** [comment] 2021-11-03 14:24
@JoseCaetanoNeto I have created different properties at Catalog and Category level, but still cannot reproduce your problem.
And you have denied access to your environment. Could you record a video to reproduce the problem? It would be very good.

**Comment by dvvkgd** [comment] 2021-11-10 08:55
@JoseCaetanoNeto We researched the code but couldn't find the problem. The problem still doesn't repeat itself. 
We think the problem is cache or indexing related.
Could you please provide access to your test environment again?

**Comment by JoseCaetanoNeto** [comment] 2021-11-11 12:12
Access has been released

Create an example catalog
![image](https://user-images.githubusercontent.com/20837564/141295074-444d370e-b54b-4425-a537-6b672028c634.png)

A virtual catalog has been created
![image](https://user-images.githubusercontent.com/20837564/141295469-102020f7-c8f1-4f1d-9ce6-f07b06c9d27d.png)

You can see the result in the frontend https://scrubupfront-dev.azurewebsites.net/store2/virtualcategorylevel1
![image](https://user-images.githubusercontent.com/20837564/141295678-f80e1107-1627-4724-b9a7-6e1dfa067f25.png)

**Comment by dvvkgd** [comment] 2021-11-12 09:42
@JoseCaetanoNeto 
Thank you for the data provided. We were able to reproduce the problem. We will be working on fixing the problem in the near future.

**Comment by dvvkgd** [comment] 2021-11-19 10:24
@JoseCaetanoNeto The problem is fixed in the release https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.80.0

**Comment by Vectorfield4** [comment] 2021-12-29 11:29
Hi, @JoseCaetanoNeto. I hope your problem is fixed. Feel free to reopen the issue if you have any troubles.

**Closed by Vectorfield4** 2021-12-29 11:29 UTC
