### ISSUE TITLE
Import/Export CSV function is broken for platform (Catalog module)

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-catalog#170] opened 2018-09-17 13:20 UTC
Browser: Chrome 68
OS: Windows 10

**Steps to reproduce:**
1. Open demo site or on any development environment .
2. Try to do export for any category from **Catalog** module with csv file.
3. Import same csv file.

**Expected results:**
File will be imported with errors (duplicated ids ).

**Current results:**
File is imported with exception:
FluentValidation.ValidationException: Validation failed:
-- 'Name' should not be empty.

Example of file is [here](https://bigfiles.assembla.com/spaces/proffsmagasinet/documents/download/bLnm4oQ5Kr6ikqdmr6bg7m)

**Comment by tatarincev** [comment] 2018-09-17 13:30
Duplicate of  https://github.com/VirtoCommerce/vc-module-catalog-csv-import/issues/18

**Closed** 2018-09-24 12:54 UTC
