### ISSUE TITLE
Categories & Items blade displaying categories of all catalogs not just the clicked one

### ISSUE THREAD

**Issue by wsimon** [VirtoCommerce/vc-module-catalog#622] opened 2022-08-22 23:42 UTC
Version info: 
- Browser version: Chrome 104
- Platform version: 3.82.0
- Module version: 3.66.0 but also tried with as late as 3.78.0

### Expected behavior
When having a role with multiple scoped catalogs and clicking on one, it should only show the contents of the clicked catalog instead of all scoped catalogs. 

### Actual behavior
When clicking on a catalog on the catalog blade, it opens up the new blade but the contents contain the categories and items of all scoped catalogs instead of just the clicked one. 

### Steps to reproduce
1. Create and assign a role with catalog:read scope with 2 or more scoped catalogs. (0 or 1 behave as expected)
2. Login with the user and browse the catalogs
3. When clicking on a catalog on the catalog blade, it opens up the new blade but the contents contain the categories and items of both scoped catalogs instead of just the clicked one.

**Comment by mvktsk** [comment] 2022-08-22 23:50
Task https://virtocommerce.atlassian.net/browse/VP-8159 has been created

**Comment by Dan-BV** [comment] 2022-08-26 07:44
Hello, @wsimon !
Thank you for your message!
This problem is known and has been fixed in newer versions. We recommend updating the module to version https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.83.4.
If the problem is not fixed, please let us know.

**Comment by wsimon** [comment] 2022-08-26 21:07
Thank you! Might be a few weeks but I'll get our module updated to that version and try it out.

**Closed** 2022-08-29 05:55 UTC
